language: go

matrix:
  include:
    - os: linux
      dist: bionic #18.04
      go: 1.19.x
    - os: linux
      dist: focal #20.04
      go: 1.19.x
    - os: linux
      dist: jammy #22.04
      go: 1.19.x
    - os: linux
      dist: bionic #18.04
      go: 1.20.x
    - os: linux
      dist: focal #20.04
      go: 1.20.x
    - os: linux
      dist: jammy #22.04
      go: 1.20.x
    - os: linux
      dist: bionic #18.04
      go: 1.21.x
    - os: linux
      dist: focal #20.04
      go: 1.21.x
    - os: linux
      dist: jammy #22.04
      go: 1.21.x
      services:
        - docker
      env:
        - docker
      script:
        - docker build -f Dockerfile.ubuntu .
        - docker build -f Dockerfile.alpine .

script:
  - go install ./...
  - go test -v ./...
  - CGO_ENABLED=0 go install ./...
  - CGO_ENABLED=0 go test -v ./...
