version: 2.1

commands:
  test:
    parameters:
      arch:
        default: "amd64"
        description: The target architecture.
        type: enum
        enum: ["amd64", "386"]
    steps:
      - run:
          name: "Test (<<parameters.arch>>)"
          command: |
            export GOARCH=<<parameters.arch>>
            go version
            go env
            go build ./... && go test -v ./...
            CGO_ENABLED=0 go build ./... && CGO_ENABLED=0 go test -v ./...

jobs:

  go121:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - test:
          arch: "amd64"
      - test:
          arch: "386"

  go120:
    docker:
      - image: cimg/go:1.20
    steps:
      - checkout
      - test:
          arch: "amd64"
      - test:
          arch: "386"

  go119:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - test:
          arch: "amd64"
      - test:
          arch: "386"



workflows:
  version: 2
  testing:
    jobs:
      - go121
      - go120
      - go119
